/** store **/

import create from 'zustand';

const useStore = create((set, get) => {
  return {
    navigation: {
      pages: {
        home: {
          active: true,
          link: '/home',
          title: 'Home',
          icon: 'faHome',
        },
        portfolio: {
          active: false,
          link: '/portfolio',
          title: 'Portfolio',
          icon: 'faImages',
        },
        contact: {
          active: false,
          link: '/contact',
          title: 'Contact',
          icon: 'faEnvelope',
        },
        resume: {
          active: false,
          link: '/resume',
          title: 'Resume',
          icon: 'faUser',
        },
      },
      toggle: (page) =>
        set((state) => ({
          navigation: {
            ...state.navigation,
            pages: Object.keys(state.navigation.pages).reduce((accumulator, key) => ({ ...accumulator, [key]: { ...accumulator[key], active: key === page } }), state.navigation.pages),
          },
        })),
    },
    carousel: {
      midIndex: 3,
      setMidIndex: (midIndex) => set((state) => ({ carousel: { ...state.carousel, midIndex: midIndex } })),
      shift: (direction) => {
        switch (direction) {
          case 'prev':
            set((state) => ({
              carousel: {
                ...state.carousel,
                items: [...state.carousel.items.slice(-1), ...state.carousel.items.slice(0, state.carousel.items.length - 1)].map((item, index) => ({
                  ...item,
                  active: index === state.carousel.midIndex,
                })),
              },
            }));
            break;

          case 'next':
            set((state) => ({
              carousel: {
                ...state.carousel,
                items: [...state.carousel.items.slice(1, state.carousel.items.length), state.carousel.items[0]].map((item, index) => ({
                  ...item,
                  active: index === state.carousel.midIndex,
                })),
              },
            }));
            break;
        }
      },
      item: {
        update: (updatedItem) => {
          const itemIndex = get().carousel.items.findIndex((item) => item.name === updatedItem.name);
          set((state) => ({
            carousel: {
              ...state.carousel,
              items: [...state.carousel.items.slice(0, itemIndex), updatedItem, ...state.carousel.items.slice(itemIndex + 1)],
            },
          }));
        },
      },
      items: [
        {
          name: 'indaba',
          duration: { from: '2012', to: '2015' },
          active: true,
          images: {
            xs: [{ status: 'no-image', src: 'images/portfolio/indaba/xs.mts-cic-mobile-screens.png' }],
            lg: [
              {
                src: 'images/portfolio/indaba/lg.mc-2.1-mobile-screens-group-edit-ui-lightness.png',
                description: 'v1 real-time content API emulator and editor panels.',
                status: 'no-image',
              },
              {
                src: 'images/portfolio/indaba/lg.mc-2.1-mobile-screens-group-edit-ui-lightness-errors.png',
                description: 'v1 content navigation and editor error handling panels.',
                status: 'no-image',
              },
              {
                src: 'images/portfolio/indaba/lg.mc-2.1-mobile-screens-group-edit-ui-lightness-success.png',
                description: 'v1 content navigation and editor submit success panels.',
                status: 'no-image',
              },
              {
                src: 'images/portfolio/indaba/lg.mc-2.1-mobile-screens-group-edit-emulator-ui-lightness-success.png',
                description: 'v1 real-time content API emulator and editor submit success panels.',
                status: 'no-image',
              },
              {
                src: 'images/portfolio/indaba/lg.mc-2.1-mobile-screens-root-ui-darkness.png',
                description: 'v1 content navigation and editor panels',
                status: 'no-image',
              },
              {
                src: 'images/portfolio/indaba/lg.mc-2.1-mobile-screens-group-demographics-edit-vader.png',
                description: 'v1 content navigation and editor panels',
                status: 'no-image',
              },
              {
                src: 'images/portfolio/indaba/lg.mc-2.1-mobile-screens-group-emulator-vader.png',
                description: 'v1 real-time content API emulator and editor panels',
                status: 'no-image',
              },
              {
                src: 'images/portfolio/indaba/lg.mts-cic-mobile-screens.png',
                description: 'v2 content navigation, real-time API emulator and editor responsive panels.',
                status: 'no-image',
              },
              {
                src: 'images/portfolio/indaba/lg.mts-cic-access-control.png',
                description: 'v2 user administration.',
                status: 'no-image',
              },
            ],
          },
          header: 'Indaba Mobile',
          brief: 'Java/PHP chat platform. Developed content management, surveys and reporting.',
          technologies: ['jquery', 'java', 'spring-framework', 'mysql', 'cassandra'],
        },
        {
          name: 'invent',
          duration: { from: '2015', to: '2017' },
          active: false,
          images: {
            xs: [{ status: 'no-image', src: 'images/portfolio/invent/xs.clicks.repeat-prescription.png' }],
            lg: [
              {
                src: 'images/portfolio/invent/lg.clicks.repeat-prescription.png',
                description: 'Java fullstack B2B eCommerce on Hybris (spring) of schema, models, services and frontend clients.',
                status: 'no-image',
              },
            ],
          },
          header: 'Invent Commerce',
          brief: 'Java fullstack B2B eCommerce on Hybris (spring) of schema, services and frontend.',
          technologies: ['jquery', 'hybris', 'spring-framework', 'mysql'],
        },
        {
          name: 'pepkor',
          duration: { from: '2019', to: '2020' },
          active: false,
          images: {
            xs: [{ status: 'no-image', src: 'images/portfolio/pepkor/xs.pepkor-it.png' }],
            lg: [
              {
                src: 'images/portfolio/pepkor/lg.pepkor-it.png',
                description: 'Java (spring-boot, microservices) backend integration of POS and ERP systems.',
                status: 'no-image',
              },
            ],
          },
          header: 'PEPKOR',
          brief: 'Java (spring-boot, microservices) backend integration of POS and ERP systems.',
          technologies: ['java', 'spring-boot', 'mysql'],
        },
        {
          name: 'personal',
          duration: { from: '2001', to: '2021' },
          active: false,
          images: {
            xs: [{ status: 'no-image', src: 'images/portfolio/personal/xs.engine-1.png' }],
            lg: [
              { status: 'no-image', src: 'images/portfolio/personal/lg.engine-1.png' },
              { status: 'no-image', src: 'images/portfolio/personal/lg.engine-2.png' },
              { status: 'no-image', src: 'images/portfolio/personal/lg.engine-3.png' },
              { status: 'no-image', src: 'images/portfolio/personal/lg.engine-4.png' },
              { status: 'no-image', src: 'images/portfolio/personal/lg.engine-5.png' },
              { status: 'no-image', src: 'images/portfolio/personal/lg.engine-6.png' },
              { status: 'no-image', src: 'images/portfolio/personal/lg.engine-7.png' },
            ],
          },
          header: 'Personal',
          brief: 'Personal projects.',
          technologies: ['react', 'webgl', 'three', 'bootstrap'],
        },
        {
          name: 'ucook',
          duration: { from: '2018', to: '2019' },
          active: false,
          images: {
            xs: [{ status: 'no-image', src: 'images/portfolio/ucook/xs.meal-kits.png' }],
            lg: [
              {
                src: 'images/portfolio/ucook/lg.meal-kits.png',
                description: '',
                status: 'no-image',
              },
              {
                src: 'images/portfolio/ucook/lg.meal-kit-subscriptions.png',
                description: '',
                status: 'no-image',
              },
              {
                src: 'images/portfolio/ucook/lg.delivery-locations.png',
                description: '',
                status: 'no-image',
              },
            ],
          },
          header: 'uCook',
          brief: 'Node fullstack of B2C eCommerce on custom platform.',
          technologies: ['postgresql', 'graphql-server', 'react', 'typescript'],
        },
        {
          name: 'cognician',
          duration: { from: '2017', to: '2018' },
          active: false,
          images: {
            xs: [{ status: 'no-image', src: 'images/portfolio/cognician/xs.cognician.png' }],
            lg: [
              {
                src: 'images/portfolio/cognician/lg.cognician.png',
                description: 'Clojure fullstack of client bespoke control panels.',
                status: 'no-image',
              },
            ],
          },
          header: 'Cognician',
          brief: 'Clojure fullstack of client bespoke control panels.',
          technologies: ['clojure', 'clojure-script', 'reagent', 'datomic'],
        },
        {
          name: 'glanbia',
          duration: { from: '2017', to: '2017' },
          active: false,
          images: {
            xs: [{ status: 'no-image', src: 'images/portfolio/glanbia/xs.glanbia.png' }],
            lg: [
              {
                status: 'no-image',
                description: 'Java backend of B2B eCommerce on Hybris (spring) of address and payment models.',
                src: 'images/portfolio/glanbia/lg.glanbia.png',
              },
            ],
          },
          header: 'Glanbia',
          brief: 'Java backend of B2B eCommerce on Hybris (spring) of address and payment models.',
          technologies: ['spring-boot', 'hybris', 'postgresql'],
        },
      ],
    },
    log: {
      messages: [{ date: new Date(), id: 'appInitial', status: 'success', text: 'Welcome.' }],
      max: 512,
      add: (message) => {
        set((state) => ({
          log: {
            ...state.log,
            messages: [...(state.log.messages.length >= state.log.max ? state.log.messages.slice(state.log.max * -1) : state.log.messages), message],
          },
        }));
      },
      delete: (message) => {
        set((state) => ({
          log: {
            ...state.log,
            messages: [...state.log.messages.filter((item) => item !== message)],
          },
        }));
      },
    },
    tech: {
      javascript: {
        link: '#tech-javascript',
        text: 'Javascript',
        title: 'Javascript',
        description: 'Interpreted language with first-class functions.',
        icon: 'faJs',
        months: 120,
        proficiency: 8,
        current: true,
      },
      react: {
        link: '#tech-react',
        text: 'React',
        title: 'React',
        description: 'Library for building user interfaces.',
        icon: 'faReact',
        months: 48,
        proficiency: 8,
        current: true,
      },
      redux: {
        link: '#tech-redux',
        text: 'Redux',
        title: 'Redux',
        description: 'Library for managing state.',
        icon: 'Redux',
        months: 36,
        proficiency: 7,
        current: true,
      },
      typescript: {
        link: '#tech-typescript',
        text: 'TypeScript',
        title: 'TypeScript',
        description: 'Javascript with static type definitions.',
        icon: 'TypeScript',
        months: 36,
        proficiency: 6,
        current: true,
      },
      node: {
        link: '#tech-node',
        text: 'Node',
        title: 'Node',
        description: 'Javascript runtime environment.',
        icon: 'faNodeJs',
        months: 36,
        proficiency: 7,
        current: true,
      },
      express: {
        link: '#tech-express',
        text: 'Express',
        title: 'Express',
        description: 'Framework for building server side APIs',
        icon: 'Express',
        months: 36,
        proficiency: 7,
        current: true,
      },
      apollo: {
        link: '#tech-apollo',
        text: 'Apollo',
        title: 'Apollo',
        description: 'GraphQL implementation for Node.',
        icon: 'Apollo',
        months: 24,
        proficiency: 6,
        current: true,
      },
      html5: {
        link: '#tech-html5',
        text: 'HTML5',
        title: 'HTML5',
        description: 'HyperText Markup Language.',
        icon: 'faHtml5',
        months: 120,
        proficiency: 9,
        current: true,
      },
      css: {
        link: '#tech-css3',
        text: 'Css3',
        title: 'Css3',
        description: 'Stylesheet language describing presentation.',
        icon: 'faCss3Alt',
        months: 120,
        proficiency: 9,
        current: true,
      },
      sass: {
        link: '#tech-sass',
        text: 'Sass',
        title: 'Sass',
        description: 'Css extension language.',
        icon: 'faSass',
        months: 60,
        proficiency: 7,
        current: true,
      },
      webgl: {
        link: '#tech-webgl',
        text: 'WebGL',
        title: 'WebGL',
        description: 'Javascript API for rendering 2D and 3D.',
        icon: 'WebGL',
        months: 24,
        proficiency: 6,
        current: true,
      },
      gis: {
        link: '#tech-gis',
        text: 'GIS',
        title: 'GIS',
        description: 'Geographic Information System mapping.',
        icon: 'faMapMarkedAlt',
        months: 36,
        proficiency: 5,
        current: true,
      },
      three: {
        link: '#tech-three',
        text: 'Three',
        title: 'Three',
        description: 'Library for WebGL.',
        icon: 'Three',
        months: 24,
        proficiency: 6,
        current: true,
      },
      r3f: {
        link: '#tech-r3f',
        text: 'React Three Fiber',
        title: 'React-Three-Fiber',
        description: 'React renderer for Three',
        icon: '',
        months: 24,
        proficiency: 6,
        current: true,
      },
      zustand: {
        link: '#tech-zustand',
        text: 'Zustand',
        title: 'Zustand',
        description: 'Library for managing state.',
        icon: '',
        months: 12,
        proficiency: 7,
        current: true,
      },
      d3: {
        link: '#tech-d3',
        text: 'D3',
        title: 'D3',
        description: 'Library for data-visualization.',
        icon: 'D3',
        months: 36,
        proficiency: 5,
        current: true,
      },
      'react-spring': {
        link: '#tech-react-spring',
        text: 'React Spring',
        title: 'React Spring',
        description: 'Library based on physics for animation.',
        icon: 'ReactSpring',
        months: 12,
        proficiency: 4,
        current: true,
      },
      bootstrap: {
        link: '#tech-bootstrap',
        text: 'Bootstrap',
        title: 'Bootstrap',
        description: 'Framework for building applications.',
        icon: 'faBootstrap',
        months: 60,
        proficiency: 8,
        current: true,
      },
      antd: {
        link: '#tech-antd',
        text: 'AntD',
        title: 'AntD',
        description: 'Framework for building UI components.',
        icon: 'AntD',
        months: 8,
        proficiency: 5,
        current: false,
      },
      'styled-components': {
        link: '#tech-styled-components',
        text: 'Styled Components',
        title: 'Styled-Components',
        description: 'Library for building component-level styles.',
        icon: 'StyledComponents',
        months: 12,
        proficiency: 5,
        current: true,
      },
      leaflet: {
        link: '#tech-leaflet',
        text: 'Leaflet',
        title: 'Leaflet',
        icon: 'Leaflet',
        description: 'Library for interactive maps.',
        months: 8,
        proficiency: 6,
        current: true,
      },
      cesium: {
        link: '#tech-cesium',
        text: 'Cesium',
        title: 'Cesium',
        description: 'Library for interactive, 3D maps.',
        icon: 'Cesium',
        months: 3,
        proficiency: 5,
        current: true,
      },
      'graphql-client': {
        link: '#tech-graphql-client',
        text: 'GraphQL Client',
        title: 'GraphQL Client',
        description: 'Client side query language for APIs',
        icon: 'GraphQL',
        months: 24,
        proficiency: 8,
        current: true,
      },
      'graphql-server': {
        link: '#tech-graphql-server',
        text: 'GraphQL Server',
        title: 'GraphQL Server',
        description: 'Server side query language for APIs',
        icon: 'GraphQL',
        months: 24,
        proficiency: 6,
        current: true,
      },
      jsdoc: {
        link: '#tech-jsdoc',
        text: 'JSDoc',
        title: 'JSDoc',
        description: 'An API documentation generator.',
        icon: '',
        months: 48,
        proficiency: 8,
        current: true,
      },
      eslint: {
        link: '#tech-eslint',
        text: 'ESLint',
        title: 'ESLint',
        description: 'Tool for reporting on patterns in code.',
        icon: 'ESLint',
        months: 48,
        proficiency: 8,
        current: true,
      },
      prettier: {
        link: '#tech-prettier',
        text: 'Prettier',
        title: 'Prettier',
        description: 'A code formatter.',
        icon: 'Prettier',
        months: 48,
        proficiency: 8,
        current: true,
      },
      jest: {
        link: '#tech-jest',
        text: 'Jest',
        title: 'Jest',
        description: 'Unit and integration testing.',
        icon: 'Jest',
        months: 48,
        proficiency: 7,
        current: true,
      },
      enzyme: {
        link: '#tech-enzyme',
        text: 'Enzyme',
        title: 'Enzyme',
        description: 'Unit and integration testing.',
        icon: 'AirBNB',
        months: 48,
        proficiency: 6,
        current: true,
      },
      mocha: {
        link: '#tech-mocha',
        text: 'Mocha',
        title: 'Mocha',
        description: 'Unit and integration testing.',
        icon: 'Mocha',
        months: 48,
        proficiency: 6,
        current: true,
      },
      chai: {
        link: '#tech-chai',
        text: 'Chai',
        title: 'Chai',
        description: 'Unit and integration testing.',
        icon: 'Chai',
        months: 12,
        proficiency: 6,
        current: false,
      },
      'testing-library': {
        link: '#tech-testing-library',
        text: 'Testing Library',
        title: 'Testing-Library',
        description: 'Integration testing.',
        icon: 'ReactTestingLibrary',
        months: 6,
        proficiency: 6,
        current: true,
      },
      docker: {
        link: '#tech-docker',
        text: 'Docker',
        title: 'Docker',
        description: 'Platform for developing, running and shipping.',
        icon: 'faDocker',
        months: 60,
        proficiency: 8,
        current: true,
      },
      'schema-design': {
        link: '#tech-schema-design',
        text: 'Schema Design',
        title: 'Schema Design',
        description: 'Normalized and de-normalized data modelling.',
        icon: 'SchemaDesign',
        months: 24,
        proficiency: 7,
        current: true,
      },
      mongodb: {
        link: '#tech-mongodb',
        text: 'MongoDB',
        title: 'MongoDB',
        description: 'A document database.',
        icon: 'MongoDB',
        months: 24,
        proficiency: 7,
        current: true,
      },
      cassandra: {
        link: '#tech-cassandra',
        text: 'Cassandra',
        title: 'Cassandra',
        description: 'A NoSQL distributed database.',
        icon: 'Cassandra',
        months: 24,
        proficiency: 4,
        current: false,
      },
      mysql: {
        link: '#tech-mysql',
        text: 'MySQL',
        title: 'MySQL',
        description: 'A relational database management system. ',
        icon: 'MySQL',
        months: 120,
        proficiency: 9,
        current: true,
      },
      postgresql: {
        link: '#tech-postgresql',
        text: 'PostgreSQL',
        title: 'PostgreSQL',
        description: 'A relational database management system. ',
        icon: 'PostgreSQL',
        months: 60,
        proficiency: 8,
        current: true,
      },
      postgis: {
        link: '#tech-postgis',
        text: 'PostGIS',
        title: 'PostGIS',
        description: 'Spatial database extender for PostgreSQL.',
        icon: 'PostgreSQL',
        months: 8,
        proficiency: 5,
        current: true,
      },
      qgis: {
        link: '#tech-qgis',
        text: 'QGIS',
        title: 'QGIS',
        description: 'A GIS editor.',
        icon: 'QGIS',
        months: 8,
        proficiency: 4,
        current: true,
      },
      typeorm: {
        link: '#tech-typeorm',
        text: 'TypeORM',
        title: 'TypeORM',
        description: 'An object relational mapper.',
        icon: '',
        months: 12,
        proficiency: 6,
        current: true,
      },
      bash: {
        link: '#tech-bash',
        text: 'Bash',
        title: 'Bash',
        description: 'A linux CLI shell.',
        icon: 'Bash',
        months: 120,
        proficiency: 6,
        current: true,
      },
      linux: {
        link: '#tech-linux',
        text: 'Linux',
        title: 'Linux',
        description: 'An open source operating system.',
        icon: 'faLinux',
        months: 120,
        proficiency: 6,
        current: true,
      },
      blender: {
        link: '#tech-blender',
        text: 'Blender',
        title: 'Blender',
        description: 'A 3D creation suite.',
        icon: 'Blender',
        months: 120,
        proficiency: 5,
        current: true,
      },
      inkscape: {
        link: '#tech-inkscape',
        text: 'Inkscape',
        title: 'Inkscape',
        description: 'A vector graphics suite.',
        icon: 'Inkscape',
        months: 120,
        proficiency: 6,
        current: true,
      },
      gimp: {
        link: '#tech-gimp',
        text: 'Gimp',
        title: 'Gimp',
        description: 'An image editing suite.',
        icon: 'Gimp',
        months: 120,
        proficiency: 7,
        current: true,
      },
      arduino: {
        link: '#tech-arduino',
        text: 'Arduino',
        title: 'Arduino',
        description: 'An electronics platform.',
        icon: 'Arduino',
        months: 48,
        proficiency: 6,
        current: true,
      },
      mobile: {
        link: '#tech-mobile',
        text: 'Mobile',
        title: 'Mobile',
        description: 'Responsive mobile applications.',
        icon: 'faMobileAlt',
        months: 60,
        proficiency: 8,
        current: true,
      },
      desktop: {
        link: '#tech-desktop',
        text: 'Desktop',
        title: 'Desktop',
        description: 'Responsive desktop applications.',
        icon: 'faDesktop',
        months: 60,
        proficiency: 8,
        current: true,
      },
      java: {
        link: '#tech-java',
        text: 'Java',
        title: 'Java',
        description: 'JIT compiled, class based language.',
        icon: 'faJava',
        months: 72,
        proficiency: 6,
        current: false,
      },
      hibernate: {
        link: '#tech-hibernate',
        text: 'Hibernate',
        title: 'Hibernate',
        description: 'An object relational mapper.',
        icon: 'Hibernate',
        months: 72,
        proficiency: 7,
        current: false,
      },
      'spring-boot': {
        link: '#tech-spring-boot',
        text: 'Spring Boot',
        title: 'Spring Boot',
        description: 'Framework for creating micro-services',
        icon: 'SpringBoot',
        months: 12,
        proficiency: 6,
        current: false,
      },
      'spring-integration': {
        link: '#tech-spring-integration',
        text: 'Spring Integration',
        title: 'Spring Integration',
        description: 'Framework for lightweight messaging',
        icon: 'SpringBoot',
        months: 12,
        proficiency: 4,
        current: false,
      },
      'spring-framework': {
        link: '#tech-spring-framework',
        text: 'Spring Framework',
        title: 'Spring Framework',
        description: 'Framework for enterprise applications.',
        icon: 'SpringBoot',
        months: 72,
        proficiency: 7,
        current: false,
      },
      hybris: {
        link: '#tech-hybris',
        text: 'Hybris',
        title: 'Hybris',
        description: 'Framework for e-Commerce applications.',
        icon: 'Hybris',
        months: 12,
        proficiency: 4,
        current: false,
      },
      tomcat: {
        link: '#tech-tomcat',
        text: 'Tomcat',
        title: 'Tomcat',
        description: 'An HTTP server.',
        icon: 'Tomcat',
        months: 72,
        proficiency: 6,
        current: false,
      },
      clojure: {
        link: '#tech-clojure',
        text: 'Clojure',
        title: 'Clojure',
        description: 'LISP based functional language.',
        icon: 'Clojure',
        months: 6,
        proficiency: 4,
        current: false,
      },
      reframe: {
        link: '#tech-reframe',
        text: 'Re-Frame',
        title: 'Re-Frame',
        description: 'Clojure derivative of React and Redux.',
        icon: 'Clojure',
        months: 6,
        proficiency: 4,
        current: false,
      },
      datomic: {
        link: '#tech-datomic',
        text: 'Datomic',
        title: 'Datomic',
        description: 'Transactional database with flexible data.',
        icon: 'Datomic',
        months: 6,
        proficiency: 3,
        current: false,
      },
      'clojure-script': {
        link: '#tech-clojure-script',
        text: 'Clojure Script',
        title: 'Clojure Script',
        description: 'LISP based functional language.',
        icon: 'ClojureScript',
        months: 6,
        proficiency: 5,
        current: false,
      },
      reagent: {
        link: '#tech-reagent',
        text: 'Reagent',
        title: 'Reagent',
        description: 'React for Clojure.',
        icon: 'Reagent',
        months: 6,
        proficiency: 5,
        current: false,
      },
      php: {
        link: '#tech-php',
        text: 'PHP',
        title: 'PHP',
        description: 'Interpreted, scripting language.',
        icon: 'faPhp',
        months: 120,
        proficiency: 8,
        current: false,
      },
      jquery: {
        link: '#tech-jquery',
        text: 'jQuery',
        title: 'jQuery',
        description: 'Javascript library.',
        icon: 'JQuery',
        months: 60,
        proficiency: 7,
        current: false,
      },
      'jquery-ui': {
        link: '#tech-jquery-ui',
        text: 'jQuery UI',
        title: 'jQuery UI',
        description: 'Framework for building UI components.',
        icon: 'JQueryUI',
        months: 24,
        proficiency: 6,
        current: false,
      },
    },
    projects: [
      {
        employer: 'freelancing',
        from: '03/2018',
        to: '',
        clients: [
          {
            name: 'Solenoid Engine',
            link: 'http://functional.org.za/engine/console',
            description: 'virtual representation of real-world metrics.',
            responsibilities: ['full-stack design and development of application'],
            technologies: {
              frontend: ['react', 'zustand', 'three', 'r3f', 'bootstrap'],
              backend: ['express'],
              applications: ['blender', 'inkscape', 'gimp'],
            },
            images: {
              cover: {
                lg: { status: 'no-image', src: 'images/portfolio/personal/solenoid-engine.gif' },
                sm: { status: 'no-image', src: 'images/portfolio/personal/solenoid-engine.gif' },
              },
              xs: [{ status: 'no-image', src: 'images/portfolio/personal/xs.engine-1.png' }],
              lg: [
                { status: 'no-image', src: 'images/portfolio/personal/lg.engine-1.png' },
                { status: 'no-image', src: 'images/portfolio/personal/lg.engine-2.png' },
                { status: 'no-image', src: 'images/portfolio/personal/lg.engine-3.png' },
                { status: 'no-image', src: 'images/portfolio/personal/lg.engine-4.png' },
                { status: 'no-image', src: 'images/portfolio/personal/lg.engine-5.png' },
                { status: 'no-image', src: 'images/portfolio/personal/lg.engine-6.png' },
                { status: 'no-image', src: 'images/portfolio/personal/lg.engine-7.png' },
              ],
            },
          },
          {
            name: 'PEPKOR.it',
            link: '#',
            description: 'e-Commerce POS and ERP.',
            responsibilities: ['back-end POS and ERP integration and mapping of new client models.', 'full-stack, white-labelled stock-take client bespoke application.'],
            technologies: {
              frontend: ['typescript', 'react', 'redux', 'bootstrap'],
              backend: ['spring-boot', 'spring-integration', 'hibernate', 'mysql', 'tomcat'],
              applications: [],
            },
            images: {
              cover: {
                sm: { status: 'no-image', src: 'images/portfolio/pepkor/pepkor-it.thumb.gif' },
              },
              xs: [],
              lg: [],
            },
          },
          {
            name: 'uCook',
            link: 'http://ucook.co.za',
            description: 'e-Commerce (b2c) meal-kits.',
            responsibilities: [
              'full-stack design and development of AWS/EC2 media bucket, API and Admin modules.',
              'full-stack design and development GIS shipping and warehouse querying model against SKU size and destination for costing.',
              'full-stack design and development GIS warehouse and courier routes admin module.',
              'full-stack re-development of campaigns module from C# to node.',
            ],
            technologies: {
              frontend: ['typescript', 'react', 'styled-components', 'antd', 'leaflet', 'graphql-client'],
              backend: ['typescript', 'express', 'apollo', 'graphql-server', 'typeorm', 'postgresql', 'postgis'],
              applications: ['qgis'],
            },
            images: {
              cover: {
                sm: { status: 'no-image', src: 'images/portfolio/ucook/ucook.thumb.gif' },
              },
              xs: [{ status: 'no-image', src: 'images/portfolio/ucook/xs.meal-kits.png' }],
              lg: [
                { status: 'no-image', src: 'images/portfolio/ucook/lg.meal-kits.png' },
                { status: 'no-image', src: 'images/portfolio/ucook/lg.meal-kit-subscriptions.png' },
                { status: 'no-image', src: 'images/portfolio/ucook/lg.delivery-locations.png' },
              ],
            },
          },
          {
            name: 'Glanbia',
            link: 'https://www.glanbia.com',
            description: 'e-Commerce (b2b) Nutrition.',
            responsibilities: [
              "full-stack re-development of authentication/authorization to oAuth based on JWT's .",
              'full-stack re-development of client address models and migrations.',
              'full-stack design and development of competition client and admin modules.',
            ],
            technologies: {
              frontend: ['react', 'redux', 'bootstrap', 'material-ui'],
              backend: ['hybris', 'spring-framework', 'hibernate', 'postgresql', 'tomcat'],
              applications: ['qgis'],
            },
            images: {
              cover: {
                sm: { status: 'no-image', src: 'images/portfolio/glanbia/glanbia.thumb.gif' },
              },
              xs: [{ status: 'no-image', src: 'images/portfolio/glanbia/xs.glanbia.png' }],
              lg: [{ status: 'no-image', src: 'images/portfolio/glanbia/lg.glanbia.png' }],
            },
          },
          {
            name: 'BLOCKv',
            link: 'http://www.blockv.io',
            description: 'block-chain "vatoms" exchange.',
            responsibilities: ['front-end development and maintenance of web SDK bridge between mobile and canvas events.', 'front-end design and development of 3D test Vatoms.', 'front-end design and development of standalone AWS/EC2 bucket module.'],
            technologies: {
              frontend: ['react', 'three', 'styled-components'],
              backend: [],
              applications: ['blender', 'inkscape', 'gimp'],
            },
            images: {
              cover: {
                sm: { status: 'no-image', src: 'images/portfolio/blockv/blockv.thumb.gif' },
              },
              xs: [],
              lg: [],
            },
          },
          {
            name: 'SA Weather',
            link: 'http://functional.org.za/weather',
            description: 'real-time weather for South Africa.',
            responsibilities: ['full-stack design and development of application'],
            technologies: {
              frontend: ['typescript', 'react', 'redux', 'bootstrap', 'leaflet'],
              backend: ['express', 'apollo', 'mongodb'],
              applications: ['blender', 'inkscape', 'gimp', 'qgis'],
            },
            images: {
              cover: {
                lg: '',
                sm: '',
              },
              xs: [],
              lg: [],
            },
          },
          {
            name: 'Lotto Generator',
            link: '#',
            description: 'historical and custom weighted generator.',
            responsibilities: ['front-end design and development of application'],
            technologies: {
              frontend: ['react', 'redux', 'bootstrap'],
              backend: [],
              applications: [],
            },
            images: {
              cover: {
                sm: { status: 'no-image', src: 'images/portfolio/personal/lotto-generator.thumb.gif' },
                lg: { status: 'no-image', src: 'images/portfolio/personal/lotto-generator.gif' },
              },
              xs: [],
              lg: [
                {
                  src: 'images/portfolio/personal/lotto-generator-1.png',
                  description: '',
                  status: 'no-image',
                },
                {
                  src: 'images/portfolio/personal/lotto-generator-2.png',
                  description: '',
                  status: 'no-image',
                },
                {
                  src: 'images/portfolio/personal/lotto-generator-3.png',
                  description: '',
                  status: 'no-image',
                },
                {
                  src: 'images/portfolio/personal/lotto-generator-4.png',
                  description: '',
                  status: 'no-image',
                },
              ],
            },
          },
        ],
      },
      {
        employer: 'cognician',
        to: '08/2017',
        from: '01/2017',
        clients: [
          {
            name: 'Cognician',
            link: 'http://www.cognician.com',
            description: 'digital learning platform.',
            responsibilities: ['full-stack development of client bespoke panels.'],
            technologies: {
              frontend: ['clojure-script', 'reagent', 'styled-components'],
              backend: ['clojure', 'datomic', 'postgresql'],
              applications: [],
            },
            images: {
              cover: {
                sm: { status: 'no-image', src: 'images/portfolio/cognician/cognician.thumb.gif' },
              },
              xs: [],
              lg: [],
            },
          },
        ],
      },
      {
        employer: 'invent-commerce',
        to: '01/2017',
        from: '01/2015',
        clients: [
          {
            name: 'Clicks',
            link: 'http://www.clicks.co.za',
            description: 'e-Commerce store.',
            responsibilities: [
              'full-stack development of presentation, service and persistence layers.',
              'back-end integration of SAPC services.',
              'full-stack development of OTC pharmaceutical sales.',
              'full-stack development of patient medicines management.',
            ],
            technologies: {
              frontend: ['spring-framework', 'jquery'],
              backend: ['spring-framework', 'hybris', 'mysql'],
              applications: [],
            },
            images: {
              cover: {
                sm: { status: 'no-image', src: 'images/portfolio/invent/clicks.thumb.gif' },
              },
              xs: [],
              lg: [],
            },
          },
        ],
      },
      {
        employer: 'indaba',
        to: '01/2015',
        from: '01/2012',
        clients: [
          {
            name: 'Indaba Mobile',
            link: '#',
            description: 'White-labelled chat application.',
            responsibilities: ['full-stack development of administration console.', 'full-stack development of client bespoke consoles.', 'dev-ops of platform.', 'back-end development of services.'],
            technologies: {
              frontend: ['jquery', 'jquery-ui'],
              backend: ['php', 'spring-framework', 'mysql', 'cassandra'],
              applications: ['gimp'],
            },
            images: {
              cover: {
                sm: { status: 'no-image', src: 'images/portfolio/indaba/indaba-mobile.thumb.gif' },
              },
              xs: [{ status: 'no-image', src: 'images/portfolio/indaba/xs.mts-cic-mobile-screens.png' }],
              lg: [
                {
                  src: 'images/portfolio/indaba/lg.mc-2.1-mobile-screens-group-edit-ui-lightness.png',
                  description: 'v1 real-time content API emulator and editor panels.',
                  status: 'no-image',
                },
                {
                  src: 'images/portfolio/indaba/lg.mc-2.1-mobile-screens-group-edit-ui-lightness-errors.png',
                  description: 'v1 content navigation and editor error handling panels.',
                  status: 'no-image',
                },
                {
                  src: 'images/portfolio/indaba/lg.mc-2.1-mobile-screens-group-edit-ui-lightness-success.png',
                  description: 'v1 content navigation and editor submit success panels.',
                  status: 'no-image',
                },
                {
                  src: 'images/portfolio/indaba/lg.mc-2.1-mobile-screens-group-edit-emulator-ui-lightness-success.png',
                  description: 'v1 real-time content API emulator and editor submit success panels.',
                  status: 'no-image',
                },
                {
                  src: 'images/portfolio/indaba/lg.mc-2.1-mobile-screens-root-ui-darkness.png',
                  description: 'v1 content navigation and editor panels',
                  status: 'no-image',
                },
                {
                  src: 'images/portfolio/indaba/lg.mc-2.1-mobile-screens-group-demographics-edit-vader.png',
                  description: 'v1 content navigation and editor panels',
                  status: 'no-image',
                },
                {
                  src: 'images/portfolio/indaba/lg.mc-2.1-mobile-screens-group-emulator-vader.png',
                  description: 'v1 real-time content API emulator and editor panels',
                  status: 'no-image',
                },
                {
                  src: 'images/portfolio/indaba/lg.mts-cic-mobile-screens.png',
                  description: 'v2 content navigation, real-time API emulator and editor responsive panels.',
                  status: 'no-image',
                },
                {
                  src: 'images/portfolio/indaba/lg.mts-cic-access-control.png',
                  description: 'v2 user administration.',
                  status: 'no-image',
                },
              ],
            },
          },
        ],
      },
    ],
  };
});

export default useStore;
