/** types/carousel **/

export const types = {
  MOVE_CAROUSEL: 'MOVE_CAROUSEL',
  FETCH_CAROUSEL_IMAGE: 'FETCH_CAROUSEL_IMAGE',
  CAROUSEL_IMAGE_REQUEST: 'CAROUSEL_IMAGE_REQUEST',
  CAROUSEL_IMAGE_SUCCESS: 'CAROUSEL_IMAGE_SUCCESS',
  CAROUSEL_IMAGE_ERROR: 'CAROUSEL_IMAGE_ERROR',
  UPDATE_ITEM_STATUS: 'UPDATE_ITEM_STATUS'
} 
