import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faLinux, faHtml5, faDocker, faBootstrap, faJs, faCss3Alt, faSass, faReact, faJava, faPhp, faNodeJs } from '@fortawesome/free-brands-svg-icons';
import { faMapMarkedAlt, faMobileAlt, faDesktop } from '@fortawesome/free-solid-svg-icons';

import {
  Cesium,
  Leaflet,
  AntD,
  ReactSpring,
  D3,
  Three,
  Redux,
  GraphQL,
  JQuery,
  JQueryUI,
  CLJS,
  Bootstrap,
  Clojure,
  ClojureScript,
  Reagent,
  Datomic,
  MySQL,
  Cassandra,
  Spring,
  Hybris,
  Magento,
  Backbone,
  Zend,
  Bash,
  PostgreSQL,
  StyledComponents,
  TypeScript,
  WebGL,
  Express,
  Apollo,
  ESLint,
  Prettier,
  Jest,
  AirBNB,
  Mocha,
  Chai,
  ReactTestingLibrary,
  MongoDB,
  QGIS,
  Blender,
  Inkscape,
  Gimp,
  Arduino,
  Hibernate,
  SpringBoot,
  Tomcat,
  SchemaDesign,
} from './Svg';

export default ({ name, ...props }) => {
  const iAwesome = { faMobileAlt, faDesktop, faLinux, faDocker, faBootstrap, faMapMarkedAlt, faHtml5, faJs, faCss3Alt, faSass, faReact, faJava, faPhp, faNodeJs };
  const iSVG = {
    Express,
    Cesium,
    Leaflet,
    AntD,
    ReactSpring,
    D3,
    Three,
    TypeScript,
    Redux,
    GraphQL,
    JQuery,
    JQueryUI,
    CLJS,
    Bootstrap,
    Clojure,
    ClojureScript,
    Reagent,
    Datomic,
    MySQL,
    Cassandra,
    Spring,
    Hybris,
    Magento,
    Backbone,
    Zend,
    Bash,
    PostgreSQL,
    StyledComponents,
    WebGL,
    Apollo,
    ESLint,
    Prettier,
    Jest,
    AirBNB,
    Mocha,
    Chai,
    ReactTestingLibrary,
    MongoDB,
    QGIS,
    Blender,
    Inkscape,
    Gimp,
    Arduino,
    Hibernate,
    SpringBoot,
    Tomcat,
    SchemaDesign,
  };

  if (Object.keys(iAwesome).find((key) => key === name)) return <FontAwesomeIcon className="tech-icon" icon={iAwesome[name]} size="2x" {...props} />;
  if (Object.keys(iSVG).find((key) => key === name)) {
    const Component = iSVG[name];
    return <Component className="tech-icon" width="100%" height="26px" {...props} />;
  }
  return null;
};
